### ISSUE TITLE
User: "bare minimum" package

### ISSUE THREAD

**Issue by sofiapoh** [quaker-social-action/dte-website#2]
As a user, when I click on "bare minimum" package I can get the breakdown of what's available in that price-range so that I can take it from there.

**Comment by DuncanMcLaggan** [comment]
This would be a "direct cremation" - involves no service, body is transported straight to a crematorium. An option for those who want a very simple option, either due to preference or cost. 

No real optional pricing here - the package will come at a set cost which covers:

o   Funeral director time and overheads (professional fees)
o   Storage of body
o   Simple coffin
o   Transport of the body to the crematorium
o   Crematorium fee 
o   Doctors fee
- Return of ashes (may be a small additional cost)

Price ranges: £999 - £1600

Price difference depends on mostly the funeral director's professional fees and the costs of the crematorium (which differ region to region). 

If this is a preferred option then we recommend people to do a simple Google search for "direct cremation" or contact your local funeral director and ask if they have this option.

**Comment by DuncanMcLaggan** [comment]
Draft text for this option emailed to Richard
